name: CodeCheck

on:
  push:
    tags-ignore:
      - "*"
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-check:
    name: CodeCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ".node-version"
          cache: "npm"
      - run: npm ci
      - name: format
        run: npm run format
      - name: lint
        run: npm run lint
      - name: building
        run: npm run build
