name: LatestRelease

on:
  # Run a workflow when a release has been released
  # @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [released]

jobs:
  latest-release:
    # Do not run if the release is a prerelease or draft
    # @see https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#release
    if: ${{ github.event.release.prerelease == false && github.event.release.draft == false }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: ".node-version"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - name: building
        run: npm run build
      - name: publish
        run: npm publish --provenance --tag=latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
